steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/GoogleCloudPlatform/cloud-builders-community.git']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app', '.']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'instances', 'reset', 'INSTANCE_NAME', '--zone=ZONE', '--project=PROJECT_ID']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'scp', '--recurse', '.', 'INSTANCE_NAME:/[REMOTE_APP_DIRECTORY]', '--zone=ZONE', '--project=PROJECT_ID']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['compute', 'ssh', 'INSTANCE_NAME', '--command', 'cd /[REMOTE_APP_DIRECTORY] && docker-compose up -d', '--zone=ZONE', '--project=PROJECT_ID']
