
logsBucket: 'gs://fyp2024_bucket'
options:
  logging: GCS_ONLY

steps:
  # Package the directory into a tarball
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        tar -czf /workspace/FYP_2024.tar.gz -C /workspace .

  # Copy the tarball to the Compute Engine VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp /workspace/FYP_2024.tar.gz jason_molina@ubuntu:/home/jason_molina/ --zone europe-west1-b

  # SSH into the VM and extract the tarball
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh jason_molina@ubuntu --zone europe-west1-b --command 'sudo tar -xzf /home/jason_molina/FYP_2024.tar.gz -C /home/jason_molina'

timeout: '1200s'  # Adjust the timeout based on your needs

