
logsBucket: 'gs://fyp2024_bucket'
options:
  logging: GCS_ONLY

steps:
  
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mkdir test
        cp -r /workspace/.git/FYP_2024 /test 
        tar -czf /workspace/test.tar.gz -C /test .

  
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp /workspace/test.tar.gz jason_molina@ubuntu:/home/jason_molina/ --zone europe-west1-b

  
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh jason_molina@ubuntu --zone europe-west1-b --command 'sudo tar -xzf /home/jason_molina/test.tar.gz -C /home/jason_molina'

timeout: '1200s'  

