# logsBucket: 'gs://fyp2024_bucket'
# options:
#   logging: GCS_ONLY
# steps:
#   # Step 1: Set up Python environment and install dependencies
# #   - name: 'python:3.10'
# #     entrypoint: 'bash'
# #     args:
# #       - '-c'
# #       - |
# #         python -m venv antenv
# #         source antenv/bin/activate
# #         python -m pip install --upgrade pip
# #         pip install setuptools

    
# #   - name: 'ubuntu'
# #     entrypoint: 'bash'
# #     args:
# #       - '-c'
# #       - |
# #         tar -czf build.tar.gz .

  
# # artifacts:
# #   objects:
# #     location: 'gs://fyp2024_bucket/build-artifacts/'
# #     paths:
# #         - 'build.tar.gz'

# # - name: 'gcr.io/cloud-builders/gcloud'
# #   entrypoint: 'bash'
# #   args:
# #     - '-c'
# #     - |
# #       gcloud compute scp build.tar.gz jason_molina@ubuntu:/home/jason_molina/
# #       gcloud compute ssh ubuntu@your-vm-name --command="tar -xzf /home/jason_molina/build.tar.gz -C /home/jason_molina/"

# - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       gcloud compute scp /home/jason_molina/FYP_2024/fyp.service jason_molina@ubuntu:/etc/systemd/system/
#       gcloud compute ssh jason_molina@ubuntu: --command="\
#         sudo systemctl daemon-reload && \
#         sudo systemctl enable fyp.service && \
#         echo 'Service file deployed and enabled'"

  
# - name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args:
#     - '-c'
#     - |
#       gcloud compute ssh jason_molina@ubuntu: --command="\
#         sudo chmod 755 /home/ubuntu/scripts/*.sh && \
#         sudo chown root:root /home/ubuntu/scripts/*.sh && \
#         echo 'Permissions set' && \
#         sudo /home/ubuntu/scripts/install_dependencies.sh && \
#         sudo /home/ubuntu/scripts/start_app.sh && \
#         echo 'Application started'"

# timeout: 1200s  

logsBucket: 'gs://fyp2024_bucket'
options:
  logging: GCS_ONLY

# steps:
#   # Assuming you want to include these steps, uncomment and correct the indentation and command syntax.
#   # - name: 'python:3.10'
#   #   entrypoint: 'bash'
#   #   args:
#   #     - '-c'
#   #     - |
#   #       python -m venv antenv
#   #       source antenv/bin/activate
#   #       python -m pip install --upgrade pip
#   #       pip install setuptools

#   # - name: 'ubuntu'
#   #   entrypoint: 'bash'
#   #   args:
#   #     - '-c'
#   #     - |
#   #       tar -czf build.tar.gz .

#   - name: 'gcr.io/cloud-builders/gcloud'
#     entrypoint: 'bash'
#     args:
#       - '-c'
#       - |
#         gcloud compute ssh jason_molina@ubuntu --command="\
#           sudo cp /home/jason_molina/FYP_2024/FYP_2024 /home/jason_molina/" --zone europe-west1-b

#   #       gcloud compute scp build.tar.gz jason_molina@ubuntu:/home/jason_molina/ --zone europe-west1-b
#   #       gcloud compute ssh jason_molina@ubuntu --command="tar -xzf /home/jason_molina/build.tar.gz -C /home/jason_molina/" --zone europe-west1-b

#   # - name: 'gcr.io/cloud-builders/gcloud'
#   #   entrypoint: 'bash'
#   #   args:
#   #     - '-c'
#   #     - |
#   #       gcloud compute scp jason_molina/FYP_2024/FYP_2024/scripts/fyp.service jason_molina@ubuntu:/etc/systemd/system/ --zone europe-west1-b
#   #       gcloud compute ssh jason_molina@ubuntu --command="\
#   #         sudo systemctl daemon-reload && \
#   #         sudo systemctl enable fyp.service && \
#   #         echo 'Service file deployed and enabled'" --zone europe-west1-b

#   # - name: 'gcr.io/cloud-builders/gcloud'
#   #   entrypoint: 'bash'
#   #   args:
#   #     - '-c'
#   #     - |
#   #       gcloud compute ssh jason_molina@ubuntu --command="\
#   #         sudo chmod 755 /home/jason_molina/scripts/*.sh && \
#   #         sudo chown root:root /home/jason_molina/scripts/*.sh && \
#   #         echo 'Permissions set' && \
#   #         sudo /home/jason_molina/scripts/install_dependencies.sh && \
#   #         sudo /home/jason_molina/scripts/start_app.sh && \
#   #         echo 'Application started'" --zone europe-west1-b

# # timeout: 1200s

steps:
  # # Package the directory into a tarball
  # - name: 'ubuntu'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       tar -czf /workspace/.git/FYP_2024.tar.gz -C /workspace . 

  # Copy the tarball to the Compute Engine VM
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh jason_molina@ubuntu --command="\
          tar -czf /home/jason_molina/FYP_2024/FYP_2024/FYP_2024.tar.gz /home/jason_molina/FYP_2024/FYP_2024 ." --zone europe-west1-b 

  # SSH into the VM and extract the tarball
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh jason_molina@ubuntu --zone europe-west1-b --command 'sudo tar -xzf /home/jason_molina/FYP_2024/FYP_2024.tar.gz -C /home/jason_molina'

  # - name: 'gcr.io/cloud-builders/gcloud'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       gcloud compute ssh jason_molina@ubuntu --command="\
  #         sudo chmod 755 /home/jason_molina/scripts/*.sh && \
  #         sudo chown root:root /home/jason_molina/scripts/*.sh && \
  #         echo 'Permissions set' && \
  #         sudo /home/jason_molina/scripts/install_dependencies.sh && \
  #         sudo /home/jason_molina/scripts/start_app.sh && \
  #         echo 'Application started'" --zone europe-west1-b

timeout: '1200s'  # Adjust the timeout based on your needs

