
logsBucket: 'gs://fyp2024_bucket'
options:
  logging: GCS_ONLY

steps:
  
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        tar -czf /workspace/.git/JMolina3192/FYP_2024.tar.gz -C /workspace .

  
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute scp /workspace/.git/JMolina3192/FYP_2024.tar.gz jason_molina@ubuntu:/home/jason_molina/ --zone europe-west1-b

  
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute ssh jason_molina@ubuntu --zone europe-west1-b --command 'sudo tar -xzf /home/jason_molina/FYP_2024.tar.gz -C /home/jason_molina'

timeout: '1200s'  

