logsBucket: 'gs://fyp2024_bucket'
options:
  logging: GCS_ONLY
steps:
  # Step 1: Set up Python environment and install dependencies
- name: 'python:3.10'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      python -m venv antenv
      source antenv/bin/activate
      python -m pip install --upgrade pip
      pip install setuptools

  # Step 2: Archive the build (assumed output to workspace which is /workspace by default)
- name: 'ubuntu'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      tar -czf build.tar.gz .

  #Artifacts (optional step if you need to store build artifacts in Google Cloud Storage)
artifacts:
  objects:
    location: 'gs://fyp2024_bucket/build-artifacts/'
    paths:
        - 'build.tar.gz'

  # Deploy steps
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute scp build.tar.gz jason_molina@ubuntu:/home/jason_molina/
      gcloud compute ssh ubuntu@your-vm-name --command="tar -xzf /home/jason_molina/build.tar.gz -C /home/jason_molina/"

  # Copy and set up systemd service
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute scp /home/jason_molina/FYP_2024/fyp.service jason_molina@ubuntu:/etc/systemd/system/
      gcloud compute ssh jason_molina@ubuntu: --command="\
        sudo systemctl daemon-reload && \
        sudo systemctl enable fyp.service && \
        echo 'Service file deployed and enabled'"

  # Set permissions and execute scripts
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud compute ssh jason_molina@ubuntu: --command="\
        sudo chmod 755 /home/ubuntu/scripts/*.sh && \
        sudo chown root:root /home/ubuntu/scripts/*.sh && \
        echo 'Permissions set' && \
        sudo /home/ubuntu/scripts/install_dependencies.sh && \
        sudo /home/ubuntu/scripts/start_app.sh && \
        echo 'Application started'"

timeout: 1200s  # Timeout for the whole build
